[tool.poetry]
name = "crawler"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
crawlee = {version = "*", extras = ["beautifulsoup"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
